const { test } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const mongoose = require('mongoose');
const Order = require('../src/models/Order');
const Route = require('../src/models/TransportRoute');
const Payment = require('../src/models/PaymentTransaction');
const Incident = require('../src/models/Incident');
const workflow = require('../src/controllers/operationsWorkflowController');
const recovery = require('../src/controllers/recoveryController');
const oid = () => new mongoose.Types.ObjectId();
const call = async (fn, req) => {
  const res = { code: 200, status(code) { this.code = code; return this; }, json(body) { this.body = body; return this; } };
  await fn({ get: () => '', ...req }, res, error => { res.code = error.statusCode || 500; res.body = { message: error.message }; }); return res;
};
test('MongoDB reservations, payout CAS, GPS-less SOS and recovery safety', { timeout: 30000 }, async t => {
  const dbName = `cbrt_recovery_test_${randomUUID().replaceAll('-', '')}`;
  await mongoose.connect('mongodb://127.0.0.1:27017', { dbName, serverSelectionTimeoutMS: 5000 });
  t.after(async () => { assert.equal(mongoose.connection.name, dbName); assert.match(dbName, /^cbrt_recovery_test_[a-f0-9]{32}$/); await mongoose.connection.dropDatabase(); await mongoose.disconnect(); });
  await Promise.all([Order.init(), Route.init(), Payment.init(), Incident.init()]);
  const manager = { _id: oid(), effectivePermissions: ['booking:approve', 'user:manage'] };
  const horseId = oid(); const customerId = oid();
  const orderData = () => ({ bookingCode: randomUUID(), customerId, horseIds: [horseId], origin: { address: 'HCM', countryCode: 'VN', coordinates: [106.7008, 10.7769] }, destination: { address: 'HN', countryCode: 'VN', coordinates: [105.8342, 21.0278] }, destinationStopId: 'VN-HAN', requestedDepartureDate: new Date(), pricing: { totalAmountVnd: 1000 } });
  const bookings = await Promise.allSettled([Order.create(orderData()), Order.create(orderData())]);
  assert.equal(bookings.filter(x => x.status === 'fulfilled').length, 1, 'one concurrent horse reservation wins');
  assert.equal(bookings.find(x => x.status === 'rejected').reason.code, 11000);
  const order = bookings.find(x => x.status === 'fulfilled').value;
  const vehicleId = oid(), driverId = oid(), escortId = oid();
  const routeData = () => ({ orderId: oid(), vehiclePlateNumber: 'TEST', vehicleId, driverId, escortId });
  const trips = await Promise.allSettled([Route.create({ ...routeData(), orderId: order._id }), Route.create(routeData())]);
  assert.equal(trips.filter(x => x.status === 'fulfilled').length, 1, 'one concurrent vehicle/person assignment wins');
  const route = trips.find(x => x.status === 'fulfilled').value;
  await Route.updateOne({ _id: route._id }, { $set: { orderId: order._id } });
  await Order.updateOne({ _id: order._id }, { $set: { status: 'CANCELLED' } });
  assert.equal((await Order.findById(order._id)).activeReservation, false);
  const later = await Order.create(orderData());
  await Order.updateOne({ _id: later._id }, { $set: { status: 'CANCELLED' } });
  await Payment.create({ orderId: order._id, customerId, txnRef: randomUUID(), status: 'PAID', amountVnd: 1000, expiresAt: new Date() });
  const request = { params: { id: String(order._id) }, user: manager };
  let response = await call(workflow.update, { ...request, body: { action: 'REQUEST_EXCEPTION', version: 0, kind: 'REFUND', amountVnd: 500, reason: 'Hủy trước khi chạy', evidence: 'TEST-REF' } });
  assert.equal(response.code, 200, JSON.stringify(response.body));
  const itemId = String((await Order.findById(order._id)).exceptionRequests[0]._id);
  response = await call(workflow.update, { ...request, body: { action: 'REVIEW_EXCEPTION', version: 1, itemId, status: 'APPROVED', reason: 'Đã đối chiếu' } });
  assert.equal(response.code, 200, JSON.stringify(response.body));
  const payout = () => call(workflow.update, { ...request, body: { action: 'EXECUTE_EXCEPTION', version: 2, itemId, reference: 'BANK-TEST-1', confirmTransferred: true } });
  const results = await Promise.all([payout(), payout()]);
  assert.equal(results.filter(x => x.code === 200).length, 1);
  assert.equal(results.filter(x => x.code === 409).length, 1);
  assert.equal((await Order.findById(order._id)).exceptionRequests[0].status, 'EXECUTED');
  response = await call(workflow.update, { ...request, body: { action: 'REQUEST_EXCEPTION', version: 3, kind: 'REFUND', amountVnd: 600, reason: 'Refund request exceeding remaining amount', evidence: 'TEST-OVER' } });
  assert.equal(response.code, 200);
  const overId = String((await Order.findById(order._id)).exceptionRequests[1]._id);
  response = await call(workflow.update, { ...request, body: { action: 'EXECUTE_EXCEPTION', version: 4, itemId: overId, reference: 'BANK-TEST-2', confirmTransferred: true } });
  assert.equal(response.code, 409, 'cannot execute a pending request');
  response = await call(workflow.update, { ...request, body: { action: 'REVIEW_EXCEPTION', version: 4, itemId: overId, status: 'APPROVED', reason: 'Review test' } });
  assert.equal(response.code, 200);
  response = await call(workflow.update, { ...request, body: { action: 'EXECUTE_EXCEPTION', version: 5, itemId: overId, reference: 'BANK-TEST-2', confirmTransferred: true } });
  assert.equal(response.code, 409, 'cannot refund more than captured minus previous refunds');
  response = await call(recovery.execute, { ...request, user: { _id: customerId, effectivePermissions: [] }, body: {} });
  assert.equal(response.code, 403, 'customer cannot execute recovery');
  const missingGPS = await Incident.create({ eventId: randomUUID(), tripId: route._id, reportedBy: driverId, description: 'No GPS available', locationUnavailable: true });
  assert.equal(missingGPS.location, undefined, 'missing GPS does not make an invalid GeoJSON point');
  await Incident.updateOne({ _id: missingGPS._id }, { $set: { status: 'CLOSED' } });
  const Alert = require('../src/models/OperationalAlert'); await Alert.init();
  const watchdog = require('../src/services/operationsWatchdog');
  await Route.updateOne({ _id: route._id }, { $set: { status: 'IN_TRANSIT', currentLocation: { coordinates: [106, 10], updatedAt: new Date(Date.now() - 180000) } } });
  await watchdog.scan(); await watchdog.scan();
  assert.equal(await Alert.countDocuments({ active: true }), 1, 'watchdog deduplicates stale GPS alerts');
  await Route.updateOne({ _id: route._id }, { $set: { 'currentLocation.updatedAt': new Date() } });
  await watchdog.scan(); assert.equal(await Alert.countDocuments({ active: true }), 0);
  await Route.updateOne({ _id: route._id }, { $set: { status: 'SCHEDULED' } });
  // No live database is touched: either transactional cancellation succeeds
  // here, or standalone MongoDB rejects it without a partial write.
  await Order.updateOne({ _id: order._id }, { $set: { status: 'APPROVED' } });
  const hello = await mongoose.connection.db.admin().command({ hello: 1 });
  let finalVersion = 5;
  if (hello.setName || hello.msg === 'isdbgrid') {
    await Route.updateOne({ _id: route._id }, { $set: { waypoints: [{ sequence: 1, name: 'HN', type: 'DELIVERY', location: { coordinates: [105.8342, 21.0278] }, estimatedArrival: new Date() }] } });
    response = await call(workflow.update, { ...request, body: { action: 'REQUEST_EXCEPTION', version: 5, kind: 'DESTINATION_CHANGE', proposedStopId: 'VN-DAD', reason: 'Emergency destination test', evidence: 'TEST-DEST' } });
    assert.equal(response.code, 200, JSON.stringify(response.body));
    const destinationId = String((await Order.findById(order._id)).exceptionRequests[2]._id);
    response = await call(workflow.update, { ...request, body: { action: 'REVIEW_EXCEPTION', version: 6, itemId: destinationId, status: 'APPROVED', reason: 'Manager confirmed' } });
    assert.equal(response.code, 200);
    response = await call(recovery.execute, { ...request, body: { action: 'APPLY_DESTINATION', version: 7, itemId: destinationId, reason: 'Verified destination evidence' } });
    assert.equal(response.code, 200, JSON.stringify(response.body));
    assert.equal((await Order.findById(order._id)).destinationStopId, 'VN-DAD');
    assert.deepEqual((await Route.findById(route._id)).waypoints[0].location.coordinates, [108.2022, 16.0544]);
    await Route.updateOne({ _id: route._id }, { $set: { status: 'INCIDENT_HANDLING', preIncidentStatus: 'IN_TRANSIT', odometerStart: 100, horseMovements: [{ horseId, loadedAt: new Date() }] } });
    const replacementDriver = oid(); const replacementVehicle = oid();
    const validator = t.mock.method(require('../src/controllers/routeController'), 'validateAssignment', async () => ({ vehicle: { _id: replacementVehicle, plateNumber: 'RESCUE-TEST' } }));
    response = await call(recovery.execute, { ...request, body: { action: 'RESCUE_TRANSFER', version: 8, reason: 'Vehicle breakdown test', evidence: 'Handover signed by test witnesses', horseIds: [String(horseId)], vehicleId: String(replacementVehicle), driverId: String(replacementDriver), escortId: String(escortId), previousOdometerEnd: 120 } });
    validator.mock.restore();
    assert.equal(response.code, 200, JSON.stringify(response.body));
    let transferred = await Route.findById(route._id);
    assert.equal(transferred.rescuePending, true); assert.equal(transferred.previousVehicleDistanceKm, 20);
    const incident = await Incident.create({ eventId: randomUUID(), tripId: route._id, reportedBy: driverId, description: 'Vehicle breakdown test', status: 'IN_PROGRESS', locationUnavailable: true });
    response = await call(require('../src/controllers/incidentController').updateIncidentStatus, { user: manager, params: { id: String(incident._id) }, body: { status: 'RESOLVED', resolutionNotes: 'Must wait for new driver' } });
    assert.equal(response.code, 409);
    response = await call(workflow.update, { ...request, user: { _id: replacementDriver, effectivePermissions: [] }, body: { action: 'ACCEPT_RESCUE', version: transferred.operationsVersion, value: 200, confirmAllHorses: true } });
    assert.equal(response.code, 200, JSON.stringify(response.body));
    assert.equal((await Route.findById(route._id)).rescuePending, false);
    response = await call(require('../src/controllers/incidentController').updateIncidentStatus, { user: manager, params: { id: String(incident._id) }, body: { status: 'RESOLVED', resolutionNotes: 'New driver has accepted' } });
    assert.equal(response.code, 200);
    assert.equal((await Route.findById(route._id)).status, 'IN_TRANSIT');
    await Route.updateOne({ _id: route._id }, { $set: { status: 'SCHEDULED', horseMovements: [] } });
    finalVersion = 9;
    const fault = t.mock.method(Order.prototype, 'save', async () => { throw new Error('Injected failure after route write'); });
    response = await call(recovery.execute, { ...request, body: { action: 'CANCEL_ASSIGNED', version: finalVersion, reason: 'Rollback test' } });
    fault.mock.restore();
    assert.equal(response.code, 500);
    assert.equal((await Route.findById(route._id)).status, 'SCHEDULED', 'transaction rolls back earlier route write');
    assert.equal((await Order.findById(order._id)).status, 'APPROVED');
  }
  response = await call(recovery.execute, { ...request, body: { action: 'CANCEL_ASSIGNED', version: finalVersion, reason: 'Integration cancellation' } });
  if (hello.setName || hello.msg === 'isdbgrid') {
    assert.equal(response.code, 200, JSON.stringify(response.body));
    assert.equal((await Route.findById(route._id)).status, 'CANCELLED');
    assert.equal((await Order.findById(order._id)).status, 'CANCELLED');
  } else {
    assert.equal(response.code, 503, JSON.stringify(response.body));
    assert.equal((await Route.findById(route._id)).status, 'SCHEDULED');
    assert.equal((await Order.findById(order._id)).status, 'APPROVED');
  }
});
