// Shared Backend Constants
module.exports = {
  USER_ROLES: {
    LOGISTICS_MANAGER: 'LOGISTICS_MANAGER',
    TRANSPORT_SPECIALIST: 'TRANSPORT_SPECIALIST',
    ROUTE_COORDINATOR: 'ROUTE_COORDINATOR',
    DRIVER_ESCORT: 'DRIVER_ESCORT',
    CUSTOMER: 'CUSTOMER'
  },
  ORDER_STATUS: {
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    DOCS_PROCESSING: 'DOCS_PROCESSING',
    CLEARED_FOR_TRANSPORT: 'CLEARED_FOR_TRANSPORT',
    IN_TRANSIT: 'IN_TRANSIT',
    INCIDENT_HANDLING: 'INCIDENT_HANDLING',
    DELIVERING: 'DELIVERING',
    COMPLETED: 'COMPLETED'
  }
};
