// Master Specification V1.0 - Roles, Permissions & System Constants

const ROLES = {
  LOGISTICS_MANAGER: 'LOGISTICS_MANAGER',
  TRANSPORT_SPECIALIST: 'TRANSPORT_SPECIALIST',
  FLEET_COORDINATOR: 'FLEET_COORDINATOR',
  DRIVER: 'DRIVER',
  ESCORT: 'ESCORT',
  CUSTOMER: 'CUSTOMER'
};

const PERMISSIONS = {
  USER_MANAGE: 'user:manage',
  HORSE_CREATE_OWN: 'horse:create_own',
  HORSE_MANAGE_ALL: 'horse:manage_all',
  BOOKING_CREATE: 'booking:create',
  BOOKING_APPROVE: 'booking:approve',
  COMPLIANCE_REVIEW: 'compliance:review',
  COMPLIANCE_UPLOAD: 'compliance:upload',
  ROUTE_DISPATCH: 'route:dispatch',
  TRIP_START: 'trip:start',
  TRIP_OPERATE: 'trip:operate',
  WAYPOINT_CHECKIN: 'waypoint:checkin',
  WELFARE_LOG: 'welfare:log',
  SOS_TRIGGER: 'sos:trigger',
  SOS_MANAGE: 'sos:manage',
  POD_SIGN: 'pod:sign',
  SYNC_OFFLINE_EVENTS: 'sync:offline_events',
  AUDIT_VIEW: 'audit:view',
  ANALYTICS_VIEW: 'analytics:view'
};

// Default Master Spec Role-to-Permissions Mapping
const ROLE_PERMISSIONS = {
  [ROLES.LOGISTICS_MANAGER]: [
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.HORSE_MANAGE_ALL,
    PERMISSIONS.BOOKING_APPROVE,
    PERMISSIONS.SOS_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.ANALYTICS_VIEW
  ],
  [ROLES.TRANSPORT_SPECIALIST]: [
    PERMISSIONS.HORSE_MANAGE_ALL,
    PERMISSIONS.COMPLIANCE_REVIEW,
    PERMISSIONS.COMPLIANCE_UPLOAD
  ],
  [ROLES.FLEET_COORDINATOR]: [
    PERMISSIONS.ROUTE_DISPATCH,
    PERMISSIONS.SOS_MANAGE,
    PERMISSIONS.ANALYTICS_VIEW
  ],
  [ROLES.DRIVER]: [
    PERMISSIONS.TRIP_START,
    PERMISSIONS.TRIP_OPERATE,
    PERMISSIONS.WAYPOINT_CHECKIN,
    PERMISSIONS.SOS_TRIGGER,
    PERMISSIONS.SYNC_OFFLINE_EVENTS
  ],
  [ROLES.ESCORT]: [
    PERMISSIONS.TRIP_OPERATE,
    PERMISSIONS.WAYPOINT_CHECKIN,
    PERMISSIONS.WELFARE_LOG,
    PERMISSIONS.SOS_TRIGGER,
    PERMISSIONS.SYNC_OFFLINE_EVENTS
  ],
  [ROLES.CUSTOMER]: [
    PERMISSIONS.HORSE_CREATE_OWN,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.COMPLIANCE_UPLOAD,
    PERMISSIONS.POD_SIGN
  ]
};

const ORDER_STATUS = {
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  DOCS_PROCESSING: 'DOCS_PROCESSING',
  CLEARED_FOR_TRANSPORT: 'CLEARED_FOR_TRANSPORT',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERING: 'DELIVERING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const TRIP_STATUS = {
  SCHEDULED: 'SCHEDULED',
  IN_TRANSIT: 'IN_TRANSIT',
  INCIDENT_HANDLING: 'INCIDENT_HANDLING',
  DELIVERING: 'DELIVERING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const INCIDENT_STATUS = {
  OPEN: 'OPEN',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  ORDER_STATUS,
  TRIP_STATUS,
  INCIDENT_STATUS
};
